import { RouteContainer } from '@/components/elements/Layouts/RouteContainer'
import { Link } from '@/components/elements/Links/Link'
import { UserHeader } from '@/components/elements/User/UserHeader'
import { Button } from '@/components/ui/Button/Button'
import { IconButton } from '@/components/ui/IconButton/IconButton'
import { Paper } from '@/components/ui/Paper/Paper'
import { Popover } from '@/components/ui/Popover/Popover'
import { Skeleton } from '@/components/ui/Skeleton/Skeleton'
import { Stack } from '@/components/ui/Stack/Stack'
import { Text } from '@/components/ui/Text/Text'
import { userEmbeddingsQueryOptions } from '@/hooks/query/useQueryBase'
import { useUserFollows } from '@/hooks/query/useQueryUser'
import { useUserState } from '@/hooks/state/useUser'
import { useCurrentPubkey } from '@/hooks/useAuth'
import { dbSqlite } from '@/nostr/db'
import { palette } from '@/themes/palette.stylex'
import { spacing } from '@/themes/spacing.stylex'
import { IconSearch, IconX } from '@tabler/icons-react'
import { keepPreviousData, useInfiniteQuery, useQuery } from '@tanstack/react-query'
import { useNavigate, useSearch } from '@tanstack/react-router'
import { css, html } from 'react-strict-dom'
import { EmbeddingChart } from './EmbeddingChart'
import { FeedHeaderBase } from '../Feed/headers/FeedHeaderBase'
import type { SearchItem } from '../Search/hooks/useSearchSuggestions'
import { Search } from '../Search/Search'

export const EmbeddingsRoute = () => {
  const currentPubkey = useCurrentPubkey()
  const navigate = useNavigate({ from: '/embeddings' })
  const anchorPubkeySearch = useSearch({ from: '/embeddings', select: (x) => x.anchor_pubkey })
  const anchorPubkey = anchorPubkeySearch || currentPubkey
  const anchorUser = useUserState(anchorPubkey || '')
  const anchorLabel = anchorUser?.displayName || 'anchor'
  const follows = useUserFollows(anchorPubkey || '', { enabled: !!anchorPubkey })
  const followedPubkeys = [...new Set((follows.data?.tags || []).filter((tag) => tag[0] === 'p').map((tag) => tag[1]))]
  const followedEmbeddings = useQuery(
    userEmbeddingsQueryOptions(followedPubkeys, {
      enabled: followedPubkeys.length > 0,
    }),
  )
  const followedEmbeddingsCount = followedEmbeddings.data?.length || 0
  const followedEmbeddingsLatest = followedEmbeddings.data?.reduce((latest, event) => {
    return Math.max(latest, event.created_at)
  }, 0)

  const query = useInfiniteQuery({
    queryKey: ['explore', 'nearest-users', anchorPubkey, followedEmbeddingsCount, followedEmbeddingsLatest],
    enabled: !!anchorPubkey && (!followedPubkeys.length || followedEmbeddings.isSuccess),
    initialPageParam: 0,
    placeholderData: keepPreviousData,
    queryFn: ({ pageParam }) => dbSqlite.queryNearestUserEmbeddings(anchorPubkey!, PAGE_SIZE, pageParam),
    getNextPageParam: (lastPage, allPages) => {
      const loaded = allPages.flat().filter((entry) => !entry.is_anchor).length
      return lastPage.filter((entry) => !entry.is_anchor).length < PAGE_SIZE ? undefined : loaded
    },
  })
  const entries = query.data?.pages.flat() || []
  const nearestUsers = entries.filter((entry) => !entry.is_anchor)

  const handleSelectUser = (item: SearchItem, close: () => void) => {
    if (item.type !== 'user' && item.type !== 'user_relay') {
      return
    }

    navigate({
      search: (prev) => ({
        ...prev,
        anchor_pubkey: item.pubkey,
      }),
    })
    close()
  }

  return (
    <RouteContainer
      maxWidth='lg'
      header={<FeedHeaderBase leading='Embeddings (alpha)' />}
      headline={currentPubkey ? <EmbeddingChart entries={entries} /> : null}>
      <Stack horizontal={false} sx={styles.root} gap={2}>
        {!!anchorPubkey && (
          <>
            <Stack gap={2} align='center' sx={styles.header}>
              <Stack gap={4} horizontal={false}>
                <Stack horizontal={false} gap={2}>
                  <Text variant='headline' size='lg' sx={styles.title}>
                    Vector Embeddings
                  </Text>
                  <Text variant='body' size='lg' sx={styles.title}>
                    We are experimenting with vector embeddings, a new way to find similar users based on your graph and interactions on Nostr.
                    They are generated by a machine learning graph neural network model trained on nostr data, and can help you discovery similar
                    accounts from a specific user perspective, filter out users too far away from your graph, recommendation systems and more.
                    you can learn more here <Link style={styles.link} href='https://github.com/nosotros-social/nostr-gnn'>NostrGNN</Link>
                  </Text>
                  <Text variant='body' size='lg' sx={styles.title}>
                    This feature still very experimental and only showing users from it's local database, so it might not be accurate, this project is part of the nosfabrica <Link style={styles.link} href='https://nosfabrica.com/wotathon/'>Wotathon</Link> project.
                  </Text>
                </Stack>
              </Stack>
            </Stack>
            <Stack grow justify='space-between' align='center'>
              <Stack horizontal={false} gap={1}>
                <Text variant='title' size='lg'>
                  <Stack horizontal={false}>
                    Similar users to
                  </Stack>
                </Text>
                <Paper surface='surfaceContainerLow' outlined sx={styles.card}>
                  <Stack gap={2}>
                    <UserHeader size='lg' userAvatarProps={{ size: 'sm' }} renderEmbeddingSimilarity={true} pubkey={anchorPubkey} />
                    <IconButton onClick={() => navigate({ search: (prev) => ({ ...prev, anchor_pubkey: undefined }) })}>
                      <IconX size={20} />
                    </IconButton>
                  </Stack>
                </Paper>
              </Stack>
              <Stack>
                <Popover
                  placement='bottom-end'
                  floatingStrategy='fixed'
                  contentRenderer={({ close }) => (
                    <Paper elevation={2} outlined surface='surfaceContainerLow' sx={styles.popover}>
                      <Search
                        dense
                        placeholder='Search users'
                        suggestQuery={false}
                        suggestRelays={false}
                        onSelect={(item) => handleSelectUser(item, close)}
                      />
                    </Paper>
                  )}>
                  {({ getProps, setRef, open }) => (
                    <div ref={setRef} {...getProps()} onClick={open}>
                      <IconButton icon={<IconSearch size={20} />} aria-label='Search users' />
                    </div>
                  )}
                </Popover>
              </Stack>
            </Stack>
          </>
        )}

        {!currentPubkey ? (
          <Paper outlined surface='surfaceContainerLow' sx={styles.notice}>
            <Text variant='body' size='md'>
              Sign in to explore similar users.
            </Text>
          </Paper>
        ) : null}

        {!!currentPubkey && query.isLoading ? (
          <html.div style={styles.grid}>
            {Array.from({ length: 6 }).map((_, index) => (
              <Paper key={`nearest-loading-${index}`} outlined surface='surfaceContainerLow' sx={styles.card}>
                <Stack horizontal={false} gap={2} align='flex-start'>
                  <Stack gap={2} align='center'>
                    <Skeleton variant='circular' sx={styles.avatarSkeleton} />
                    <Skeleton sx={styles.nameSkeleton} />
                  </Stack>
                  <Stack horizontal={false} gap={0.5}>
                    <Skeleton sx={styles.scoreSkeleton} />
                    <Skeleton sx={styles.metaSkeleton} />
                  </Stack>
                </Stack>
              </Paper>
            ))}
          </html.div>
        ) : null}

        {!!currentPubkey && !query.isLoading && nearestUsers.length === 0 ? (
          <Paper outlined surface='surfaceContainerLow' sx={styles.notice}>
            <Text variant='body' size='md'>
              No local embeddings found for your account yet.
            </Text>
          </Paper>
        ) : null}

        {!!currentPubkey && nearestUsers.length > 0 ? (
          <Stack horizontal={false} gap={2}>
            <html.div style={styles.grid}>
              {nearestUsers.map((entry) => {
                const similarity = Math.max(0, Math.floor(entry.similarity * 100))
                return (
                  <html.div
                    key={`${entry.pubkey}:${entry.created_at}`}
                    onClick={() =>
                      navigate({
                        search: (prev) => ({
                          ...prev,
                          anchor_pubkey: entry.pubkey,
                        }),
                      })
                    }
                    style={[styles.linkRoot, styles.linkAction]}>
                    <Paper
                      outlined
                      surface='surfaceContainerLow'
                      sx={[styles.card, styles.card$interactive]}>
                      <Stack horizontal={false} gap={2} align='flex-start'>
                        <UserHeader pubkey={entry.pubkey} renderEmbeddingSimilarity={true} />
                        <Stack gap={2} justify='space-between' sx={styles.cardBottomRow}>
                          <Stack horizontal={false} align='flex-start' sx={styles.metrics}>
                            <Text variant='title' size='md'>
                              {similarity}
                            </Text>
                            <Text variant='body' size='sm' sx={styles.metricLabel}>
                              {`similarity score to ${anchorLabel}`}
                            </Text>
                          </Stack>
                        </Stack>
                      </Stack>
                    </Paper>
                  </html.div>
                )
              })}
            </html.div>
            {query.hasNextPage ? (
              <Stack justify='center'>
                <Button
                  variant='filledTonal'
                  onClick={() => query.fetchNextPage()}
                  disabled={query.isFetchingNextPage}>
                  Load more
                </Button>
              </Stack>
            ) : null}
          </Stack>
        ) : null}
      </Stack>
    </RouteContainer>
  )
}

const LG = '@media (max-width: 1299.95px)'
const MD = '@media (max-width: 960px)'
const PAGE_SIZE = 200

const styles = css.create({
  title: {
    maxWidth: 500,
  },
  root: {
    paddingBlock: spacing.padding4,
  },
  header: {
    width: '100%',
    marginBottom: spacing.padding2,
  },
  notice: {
    padding: spacing.padding3,
  },
  popover: {
    width: 360,
    maxWidth: 'calc(100vw - 32px)',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      [LG]: 'repeat(2, minmax(0, 1fr))',
      [MD]: 'repeat(1, minmax(0, 1fr))',
    },
    gap: spacing.padding1,
  },
  card: {
    padding: spacing.padding2,
  },
  card$interactive: {
    backgroundColor: {
      default: palette.surfaceContainerLow,
      ':hover': 'rgba(125, 125, 125, 0.06)',
    },
  },
  linkRoot: {
    scrollMarginTop: 64,
  },
  linkAction: {
    cursor: 'pointer',
  },
  metrics: {
    minWidth: 0,
  },
  cardBottomRow: {
    width: '100%',
  },
  actions: {
    marginInlineStart: 'auto',
  },
  recalculatingLabel: {
    color: palette.onSurfaceVariant,
  },
  metricLabel: {
    color: palette.onSurfaceVariant,
  },
  avatarSkeleton: {
    width: 32,
    height: 32,
  },
  nameSkeleton: {
    width: 180,
    height: 14,
  },
  metaSkeleton: {
    width: 120,
    height: 12,
  },
  scoreSkeleton: {
    width: 48,
    height: 18,
  },
  link: {
    color: palette.tertiary,
    fontWeight: 600,
  },
  search: {
    maxWidth: 250,
  },
})
